# Tensorflow Ex-1

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'1.10.0'

In [9]:
hello  = tf.constant("Hello")

In [10]:
world = tf.constant("World")

In [12]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [13]:
print(hello)

Tensor("Const_4:0", shape=(), dtype=string)


In [15]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [17]:
print(result)

b'HelloWorld'


In [22]:
var1 = tf.constant(10)
var2 = tf.constant(30)

In [20]:
#var1 + var2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [24]:
with tf.Session() as sess:
    result = sess.run(var1+var2)

In [25]:
print(result)

40


In [26]:
const = tf.constant(10)

In [27]:
mat_1 = tf.fill((5,5),10)

In [28]:
zeros = tf.zeros((5,5))

In [29]:
ones = tf.ones((5,5))

In [30]:
randn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [31]:
randu = tf.random_uniform((4,4),minval=0, maxval=1)

In [32]:
myops = [const,mat_1,zeros,ones,randn,randu]

In [33]:
sess = tf.InteractiveSession()

In [36]:
for op in myops:
    #print(sess.run(op))
    print(op.eval())
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 0.23063838  0.34309855 -0.02664246  0.06213979]
 [-1.9984337  -1.1713791   0.44753605 -1.5873471 ]
 [ 0.402648   -1.0658474  -0.7529363  -0.12797193]
 [-1.1020958   0.98242277  0.31302238 -0.90349114]]


[[0.9163345  0.8087907  0.30019975 0.7882254 ]
 [0.74402726 0.04783404 0.29741275 0.37198853]
 [0.30555332 0.50995326 0.76651525 0.28903854]
 [0.23520863 0.30358434 0.6144111  0.88183427]]




In [38]:
a = tf.constant([[1,2],[3,4]])

In [39]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [40]:
b = tf.constant([[10],[100]])

In [41]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [42]:
result = tf.matmul(a,b)

In [43]:
sess.run(result)

array([[210],
       [430]])